spring.application.name=genai-chat-assistant

server.port=8080
gemini.api.key=AQ.Ab8RN6Ln4jSWb4N42L_1MUGQXqfgMN8Oml77keeC-2YbTPw3Yg
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent